### ISSUE TITLE
Sir @viclafouch I tried to create a custom version of this project with Hindi language and Indian meme templates But was Unable to deploy on netlify or other services like that

### ISSUE THREAD

**Issue by ankushom19** [viclafouch/meme-studio#146]
While building with the command `npm run build` it generates the client and server files in dist folder but when trying to deploy it on netlify or heroku it fails

**Comment by ankushom19** [comment]
And yeah forgot to mention it run perfectly on development mode with `npm run dev`

**Comment by viclafouch** [comment]
Hello @ankushom19, if you want to have other languages, just create a PR and edit i18n files. Then, I will accept your PR ;)
